version: "3.3"
services:
  medcost:
    container_name: 'medcost'
    command: bash -c "jupyter lab --notebook-dir=/home/medcost --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ../:/home/medcost